production: &default
  adapter: redis
  url: <%= Rails.configuration.redis.url %>
  channel_prefix: <%= Rails.configuration.app.cable_channel_prefix %>

docker:
  <<: *default

development:
  <<: *default

test:
  adapter: test
