common: &default_settings
  license_key: '7e609f08382865a4fb4d437c78fda33a0e551e6c'
  app_name: Fleetyards
  monitor_mode: true
  developer_mode: false
  log_level: info
  browser_monitoring:
    auto_instrument: true
  audit_log:
    enabled: false
  capture_params: false

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"

development:
  <<: *default_settings
  monitor_mode: true
  app_name: Fleetyards (Development)
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true
