# see https://crontab.guru for help/explanation of cron lines

production: &production
  loaders_youtube_job:
    cron: '*/10 * * * *' # Every 5 Minutes
    class: 'Loaders::YoutubeJob'
    queue: 'loaders'
  loaders_rsi_news_job:
    cron: '*/15 * * * *' # Every 15 Minutes
    class: 'Loaders::RsiNewsJob'
    queue: 'loaders'
  loaders_roadmap_job:
    cron: '*/20 * * * *' # Every 20 Minutes
    class: 'Loaders::RoadmapJob'
    queue: 'loaders'
  loaders_progress_tracker_job:
    cron: '*/20 * * * *' # Every 20 Minutes
    class: 'Loaders::ProgressTrackerJob'
    queue: 'loaders'
  trade_routes_job:
    cron: '0 */2 * * *' # Every 2 Hours
    class: 'TradeRoutesJob'
  loaders_models_job:
    cron: '0 20 */1 * *' # Daily at 20:00
    class: 'Loaders::ModelsJob'
    queue: 'loaders'
  prices_job:
    cron: '0 21 */1 * *' # Daily at 21:00
    class: 'PricesJob'
  metrics_job:
    cron: '0 1 */1 * *' # Daily at 1:00
    class: 'MetricsJob'
  loaders_locations_job:
    cron: '0 3 * * 0' # Weekly on Sunday 3:00
    class: 'Loaders::LocationsJob'
    queue: 'loaders'
  admin_notifier_job:
    cron: '0 20 * * 0' # Weekly on Sunday 20:00
    class: 'Notifications::AdminJob'
    queue: 'notifications'
  loaders_loaner_job:
    cron: '0 21 * * 0' # Weekly on Sunday 21:00
    class: 'Loaders::LoanerJob'
    queue: 'loaders'
  cleanup_fleet_invite_url_job:
    cron: '0 22 * * 0' # Weekly on Sunday 22:00
    class: 'Cleanup::FleetInviteUrlJob'
    queue: 'cleanup'
  cleanup_visits_job:
    cron: '0 0 1 * *' # Monthly on the first day at 0:00
    class: 'Cleanup::VisitsJob'
    queue: 'cleanup'
