production: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "test" %>
  devise: <%= ENV["DEVISE_SECRET"] || "test" %>
  devise_jwt: <%= ENV["DEVISE_JWT_SECRET"] || 'test' %>
  jwt_expiration: <%= 24.hours.to_i %>
  devise_otp_issuer: FleetYards.net
  mailer_default_from: "FleetYards.net <info@fleetyards.net>"
  mailer_admin_mail: "FleetYards.net Admin <admin@fleetyards.net>"
  mailer_host: <%= ENV["SMTP_HOST"] %>
  mailer_port: <%= ENV["SMTP_PORT"] %>
  mailer_user: <%= ENV["SMTP_USER"] %>
  mailer_password: <%= ENV["SMTP_PASSWORD"] %>
  store_version: <%= ENV["STORE_VERSION"] || 9.2 %>
  embed_store_version: <%= ENV["EMBED_STORE_VERSION"] || 1 %>
  domain: <%= ENV["DOMAIN"] || 'fleetyards.net' %>
  frontend_endpoint: <%= ENV["FRONTEND_ENDPOINT"] || 'https://fleetyards.net' %>
  api_endpoint: <%= ENV["API_ENDPOINT"] || 'https://api.fleetyards.net/v1' %>
  admin_api_endpoint: <%= ENV["ADMIN_API_ENDPOINT"] || 'https://admin.fleetyards.net/api/v1' %>
  rsi_endpoint: <%= ENV["RSI_ENDPOINT"] || 'https://robertsspaceindustries.com' %>
  cable_endpoint: <%= ENV["CABLE_ENDPOINT"] || 'wss://api.fleetyards.net/cable' %>
  rsi_vat_percent: <%= ENV["RSI_VAT_PERCENT"] || 0 %>
  sentry_dsn: <%= ENV["SENTRY_DSN"] %>
  sentry_frontend_dsn: <%= ENV["SENTRY_FRONTEND_DSN"] %>
  sentry_csp_uri: <%= ENV["SENTRY_CSP_URI"] %>
  aws_s3_bucket: 'fleetyards'
  aws_s3_region: 'eu-west-1'
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  google_youtube_api_key: <%= ENV["GOOGLE_YOUTUBE_API_KEY"] %>
  discord_updates_endpoint: <%= ENV["DISCORD_UPDATES_ENDPOINT"] %>
  discord_sc_updates_endpoint: <%= ENV["DISCORD_SC_UPDATES_ENDPOINT"] %>

development:
  <<: *default
  domain: <%= ENV["DOMAIN"] || 'fleetyards.test' %>
  frontend_endpoint: http://fleetyards.test
  api_endpoint: http://api.fleetyards.test/v1
  admin_api_endpoint: http://admin.fleetyards.test/api/v1
  cable_endpoint: ws://api.fleetyards.test/cable
  sentry_dsn:
  sentry_frontend_dsn:

staging:
  <<: *default
  domain: <%= ENV["DOMAIN"] || 'stage.fleetyards.net' %>
  frontend_endpoint: https://stage.fleetyards.net
  api_endpoint: https://stage.fleetyards.net/api/v1
  admin_api_endpoint: https://stage.fleetyards.net/admin/api/v1
  cable_endpoint: wss://stage.fleetyards.net/cable
  aws_s3_bucket: 'fleetyards-stage'
  aws_s3_region: 'eu-central-1'

ci:
  <<: *default
  frontend_endpoint: http://localhost:8270
  api_endpoint: http://localhost:8270/api/v1
  admin_api_endpoint: http://localhost:8270/admin/api/v1
  cable_endpoint: ws://localhost:8270/cable
  sentry_dsn:
  sentry_frontend_dsn:

test:
  <<: *default
  frontend_endpoint: http://localhost:8270
  api_endpoint: http://localhost:8270/api/v1
  admin_api_endpoint: http://localhost:8270/admin/api/v1
  cable_endpoint: ws://localhost:8270/cable
  sentry_dsn:
  sentry_frontend_dsn:
