name: Check

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

env:
  RUBY_VERSION: 3.0.4

jobs:
  js-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

  yarn-audit:
    needs: js-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Check Audit DB
        run: yarn audit --groups dependencies

  ruby-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

  bundle-audit:
    needs: ruby-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Update Audit DB
        run: bundle exec bundle-audit update
      - name: Check Audit DB
        run: bundle exec bundle-audit check
